### PR TITLE
Feature/laravel 6

### PR DESCRIPTION
**Pull request by nikspyratos**
### Motivation

Implements #8 - Laravel upgrade to 6.0

### Checklist

- [X] Code follows coding conventions held in this repo
- [ ] Automated tests have been added (changes are minor and mostly to non-app logic files)
- [X] Tests are passing
- [X] Docs have been updated (if applicable)
- [X] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Install the site on local, load the pages.

### CODE REVIEW

**Review by Simply007 — APPROVED** [review]
Great job @nikolaos-spyratos. Thanks!

**Comment by Simply007** [comment]
FYI: I was forced to place a workaround back: #13 

How did you find this repository (or that specific issue)? Are you participating in Hacktoberfrest?

**Comment by nikspyratos** [comment]
Yeah, found it while searching around for php/Laravel Hacktoberfest stuff.

No conflicts between the workaround and this, so safe to merge whenever
ready.

**Comment by Simply007** [comment]
Great @nikolaos-spyratos - thanks for sharing and the pull request itself!

Feel free to pick another issue, or contact via [Gitter](gitter.im/Simply007) and we could find something else. 

Check out [Global collaborators dicsussions](https://github.com/orgs/Kentico/teams/global-collaborators) for some lat news about Kentico Open source activity.

**Pull request merged**
